### ISSUE TITLE
Problem with creating subdomain in Plesk with PHP

### ISSUE THREAD

**Issue by larrybek** [pmill/php-plesk#6] opened 2016-01-13 15:49 UTC
Hi All.

I was creating subdomain on Plesk 12.5.30 version with api:
https://github.com/pmill/php-plesk

After filling up all data it brings error in plesk:
New configuration files for the Apache web server were not created due to the errors in configuration templates: Template processing failed: file = /opt/psa/admin/conf/templates/default/domainVhost.php, error = Template_Exception: Empty content was provided for config file /var/www/vhosts/system/a22.ubicross.me/conf/httpd.conf file: /opt/psa/admin/plib/Template/Writer/Webserver/Abstract.php line: 47 code: 0. Detailed error descriptions were sent to you by email. Please resolve the issues and click here to generate broken configuration files once again or here to generate all configuration files. See the details in Configuration Troubleshooter

Can someone navigate me what is the issue I have tried all. Subdomain is creating without problem when you make it from admin but with script I got that issue.

Mention: Everything is set as it mentioned in php-plesk.

**Comment by pmill** [comment] 2016-01-13 16:54
Sorry, I no longer have access to a plesk server so I can't investigate this issue. I'm happy to accept pull requests if you manage to figure out the problem.

**Comment by pmill** [comment] 2016-02-29 20:49
Hi can you let me know whereabouts in Plesk you see the error? I'm just trying to reproduce the issue.

**Comment by pmill** [comment] 2016-03-08 12:31
Hi, as it's been over a week since the last message on this issue I'm closing it. If the issue persists please open a new issue.

**Closed by pmill** 2016-03-08 12:31 UTC
Labels: bug
